name: site-check
on: push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout workspace
        uses: actions/checkout@v4
      - name: Read the readme
        run: cat README.md
      - name: install python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      - name: Show the Python version
        run: pyhton3 --version
