name: deps
on: push
jobs:
  cache_pip_download:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: show current directory
        run: |
          pwd
          ls -la
          find . -name 'requirements.txt'
      - name: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-
      - name: install package
        run: pip install -r requirements.txt

