name: pipeline with dependent jobs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ver.outputs.version }}
    steps:
      - name: compute version
        id: ver
        run: echo "version=1.2.3" >> "$GITHUB_OUTPUT"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test that output exist
        run : |
          if [ -n {{ needs.build.outputs.version }} ]; then
            echo "The output from build job is not empty"
          fi
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: print the version number
        run: |
          echo " The version is ${{ needs.build.outputs.version }} "

