name: use a secret in workflow
on: push
jobs:
  secret_usage_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: read secret and test that it is present
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          if [ -n "$APP_TOKEN" ]; then
            echo "token is available to this step"
          fi
